### ISSUE TITLE
Add D+D speakers to mozfest.org homepage

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/2016.Mozillafestival.org#105] opened 2016-09-26 16:50 UTC
Promote D+D on mozfest.org homepage. Here's a neat [benchmark](http://go.personaldemocracy.com/) (below the fold).

**Comment by edrushka** [comment] 2016-10-05 18:45
This is a duplicate of https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/107 so I'm going to close.

**Closed as completed by edrushka** 2016-10-05 18:45 UTC
Labels: D+D
